name: Build Seatbelt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Use .NET SDK 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.0'  # Choose the latest version compatible with your project
        
    - name: Checkout repository of Seatbelt
      uses: actions/checkout@v2
      with:
        repository: GhostPack/Seatbelt
        
    - name: Build Seatbelt
      run: |
        dotnet build -c Release -p:TargetFramework=net40
        dotnet build -c Release -p:TargetFramework=net35
