name: Build Seatbelt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Checkout repository of Rubeus
      uses: actions/checkout@v3
      with:
        repository: GhostPack/Rubeus
        
    - name: Build Rubeus
      run: |
         cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
         .\MSBuild.exe $Env:GITHUB_WORKSPACE\Rubeus\Rubeus.csproj
         
    - name: Upload Rubeus Artifact
      uses: actions/upload-artifact@v4
      with:
         name: Rubeus.exe
         path: ${{ github.workspace }}\Rubeus\obj\Debug\
