name: Build Seatbelt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Checkout repository of Seatbelt
      uses: actions/checkout@v3
      with:
        repository: GhostPack/Seatbelt
        
    - name: Build Seatbelt
      run: |
         cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
         .\MSBuild.exe $Env:GITHUB_WORKSPACE\Seatbelt\Seatbelt.csproj
         
    - name: Upload Seatbelt Artifact
      uses: actions/upload-artifact@v4
      with:
         name: Seatbelt.exe
         path: ${{ env:GITHUB_WORKSPACE }}\Seatbelt\obj\Debug\
